AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.9
  Sample SAM Template for simple-dataset-generating-supporter

Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "simple-dataset-generating-supporter-${AWS::AccountId}"
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled

  PingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: simple-dataset-generating-supporter-ping
      PackageType: Image
      ImageConfig:
        Command: [ "app.ping" ]
      Architectures:
        - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /ping
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./api
      DockerTag: python3.9-v1

  PostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: simple-dataset-generating-supporter-post
      PackageType: Image
      ImageConfig:
        Command: [ "app.post" ]
      Architectures:
        - x86_64
      Events:
        MyApiGateway:
          Type: Api
          Properties:
            Path: /image
            Method: post
      Environment:
        Variables:
          MY_BUCKET_NAME: !Ref MyBucket
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./api
      DockerTag: python3.9-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyApiGateway:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  PingFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt PingFunction.Arn
  PingFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt PingFunctionRole.Arn
